# Generated by Django 5.2.8 on 2025-11-21 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0005_foodtracking_orderaddress_paymentdetail_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='order',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodordering.user'),
        ),
    ]
