# Generated by Django 5.2.8 on 2025-11-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0006_remove_paymentdetail_order_paymentdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
