# Generated by Django 5.2.8 on 2025-11-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0007_alter_paymentdetail_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
